/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(libs.guava)

    // Thymeleaf
    implementation("org.thymeleaf:thymeleaf:3.1.3.RELEASE")
    implementation("org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE")

    // Spring 6
    implementation("org.springframework:spring-core:6.2.6")
    implementation("org.springframework:spring-webmvc:6.2.6")
    implementation("org.springframework:spring-orm:6.2.6")

    // Hibernate 6
    implementation("org.hibernate.orm:hibernate-core:6.6.13.Final")
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")

    // HikariCP
    implementation("com.zaxxer:HikariCP:5.1.0")

    // Flyway
    implementation("org.flywaydb:flyway-core:10.10.0")
    implementation("org.flywaydb:flyway-database-postgresql:10.10.0")

    // PostgreSQL
    implementation("org.postgresql:postgresql:42.7.5")

    // Jakarta — provided, Tomcat сам предоставляет
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")
    implementation("jakarta.annotation:jakarta.annotation-api:2.1.1")

    // SLF4J - logging
    implementation("org.slf4j:slf4j-simple:2.0.16")

    // JBCrypt
    implementation("org.mindrot:jbcrypt:0.4")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<Exec>("deployWar") {
    dependsOn(tasks.named("clean"), tasks.named("war"))

    group = "deployment"
    description = "Cleans, builds the WAR file, and executes the deploy script."

    commandLine("bash", "${rootProject.projectDir}/deploy.sh")
}
