openweather.api.key=
openweather.data.url=
openweather.geo.url=

db.url=
db.username=
db.password=

session.duration.seconds=
session.duration.minutes=
session.duration.hours=

session.cleanup.rate.ms=

session.amount=

password.pepper=
password.rounds=

city.max.length=
